config/routes.rb
Rails.application.routes.draw do
 
  root 'home#index'

  resources :specialties

  resources :moving_tasks

  resources :moving_items

  resources :table_defs

  resources :reports do
    member do
      get :prepare
      get :exec
    end
    collection do
      get :test
      get :icon_selector
    end
  end

  resources :wings

  resources :equipment_items

  resources :space_types

  resources :equipment_models do
    member do
      get :show_modal
    end
  end

  resources :equipment_groups

  resources :requirements do
    member do
      get :show_modal
      get :show_allocated_floors
    end
  end

  resources :spaces do
    member do
      get :show_modal
    end
  end

  resources :allocations do
    member do
      get :show_modal
    end
    collection do
      get :auto_new
    end
  end

  resources :people do
    member do
      get :show_modal
      get :show_allocated_floors
    end
  end

  resources :orgs do
    member do
      get :show_allocated_floors
      get :show_right
      get :export
    end
    collection do
      get :export_all
    end
  end

  resources :floors do
    member do
      get :drawing
      get :drawing_full
      get :drawing_allocations
      get :drawing_locator
      get :edit_spaces
      get :bulk_space_type_modal
      get :bulk_coor_adjust
      get :export
      post :bulk_space_type
    end
  end

  resources :buildings do
    member do
      get :photo
      get :export
    end
  end

  match 'do_import_data', to: 'home#do_import_data', via: :post

  resources :home, only: [ :index ] do
    collection do
      get :back
      get :counter_cache_reset
      get :import_data
      get :backup
    end
  end

  resources :users do
    member do
      get :change_password_for
      post :do_change_password_for
    end
    collection do
      get :change_password
      get :do_change_language
      patch :do_change_password
    end
  end

  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}

  get 'home/index'

  

end

app/models/moving_task.rb
class MovingTask < ApplicationRecord
  belongs_to :specialty
  belongs_to :moving_item

  validates :name, :order, presence: true
  validates :order, numericality: { only_integer: true }
end

app/controllers/moving_tasks_controller.rb
class MovingTasksController < ApplicationController
  before_action :set_moving_task, only: [:show, :edit, :update, :destroy]

  # GET /moving_tasks
  # GET /moving_tasks.json
  def index
    @moving_tasks = MovingTask.all
  end

  # GET /moving_tasks/1
  # GET /moving_tasks/1.json
  def show
  end

  # GET /moving_tasks/new
  def new
    @moving_task = MovingTask.new
  end

  # GET /moving_tasks/1/edit
  def edit
  end

  # POST /moving_tasks
  # POST /moving_tasks.json
  def create
    @moving_task = MovingTask.new(moving_task_params)

    respond_to do |format|
      if @moving_task.save
        format.html { redirect_to @moving_task, notice: t('.create_ok') }
        format.json { render action: 'show', status: :created, location: @moving_task }
      else
        format.html { render action: 'new' }
        format.json { render json: @moving_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moving_tasks/1
  # PATCH/PUT /moving_tasks/1.json
  def update
    respond_to do |format|
      if @moving_task.update(moving_task_params)
        format.html { redirect_to @moving_task, notice: t('.update_ok') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @moving_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moving_tasks/1
  # DELETE /moving_tasks/1.json
  def destroy
    @moving_task.destroy
    respond_to do |format|
      format.html { redirect_to moving_tasks_url, status: 303 }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_moving_task
      @moving_task = MovingTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def moving_task_params
      params.require(:moving_task).permit(:name, :description, :specialty_id, :responsability, :order, :duration, :cost)
    end
end

app/views/moving_tasks/_form.html.haml
= simple_form_for(@moving_task) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description
    = f.association :specialty
    = f.input :responsability
    = f.input :order
    = f.input :duration
    = f.input :cost

  .form-actions
    = f.button :submit

app/views/moving_tasks/edit.html.haml
%h1= t('.editing')

= render 'form'

= link_to t('cmn.show'), @moving_task
\|
= link_to t('cmn.back'), moving_tasks_path

app/views/moving_tasks/index.html.haml
%h1= t('cmn.moving_tasks')

%table
  %tr
    %th= MovingTask.human_attribute_name(:name)
    %th= MovingTask.human_attribute_name(:description)
    %th= MovingTask.human_attribute_name(:specialty)
    %th= MovingTask.human_attribute_name(:responsability)
    %th= MovingTask.human_attribute_name(:order)
    %th= MovingTask.human_attribute_name(:duration)
    %th= MovingTask.human_attribute_name(:cost)
    %th
    %th
    %th

  - @moving_tasks.each do |moving_task|
    %tr
      %td= moving_task.name
      %td= moving_task.description
      %td= moving_task.specialty
      %td= moving_task.responsability
      %td= moving_task.order
      %td= moving_task.duration
      %td= moving_task.cost
      %td= link_to t('cmn.show'), moving_task
      %td= link_to t('cmn.edit'), edit_moving_task_path(moving_task)
      %td= link_to t('cmn.destroy'), moving_task, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to t('.new_task'), new_moving_task_path

app/views/moving_tasks/new.html.haml
%h1= t('.new')

= render 'form'

= link_to t('cmn.back'), moving_tasks_path

app/views/moving_tasks/show.html.haml
%p#notice= notice

= show_entry(@moving_task) do |e|
  = e.field :name
  = e.field :description
  = e.field :specialty
  = e.field :responsability
  = e.field :order
  = e.field :duration
  = e.field :cost

= link_to t('cmn.edit'), edit_moving_task_path(@moving_task)
\|
= link_to t('cmn.back'), moving_tasks_path