config/routes.rb
Rails.application.routes.draw do
 
  root 'home#index'

  resources :specialties

  resources :moving_tasks

  resources :moving_items

  resources :table_defs

  resources :reports do
    member do
      get :prepare
      get :exec
    end
    collection do
      get :test
      get :icon_selector
    end
  end

  resources :wings

  resources :equipment_items

  resources :space_types

  resources :equipment_models do
    member do
      get :show_modal
    end
  end

  resources :equipment_groups

  resources :requirements do
    member do
      get :show_modal
      get :show_allocated_floors
    end
  end

  resources :spaces do
    member do
      get :show_modal
    end
  end

  resources :allocations do
    member do
      get :show_modal
    end
    collection do
      get :auto_new
    end
  end

  resources :people do
    member do
      get :show_modal
      get :show_allocated_floors
    end
  end

  resources :orgs do
    member do
      get :show_allocated_floors
      get :show_right
      get :export
    end
    collection do
      get :export_all
    end
  end

  resources :floors do
    member do
      get :drawing
      get :drawing_full
      get :drawing_allocations
      get :drawing_locator
      get :edit_spaces
      get :bulk_space_type_modal
      get :bulk_coor_adjust
      get :export
      post :bulk_space_type
    end
  end

  resources :buildings do
    member do
      get :photo
      get :export
    end
  end

  match 'do_import_data', to: 'home#do_import_data', via: :post

  resources :home, only: [ :index ] do
    collection do
      get :back
      get :counter_cache_reset
      get :import_data
      get :backup
    end
  end

  resources :users do
    member do
      get :change_password_for
      post :do_change_password_for
    end
    collection do
      get :change_password
      get :do_change_language
      patch :do_change_password
    end
  end

  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}

  get 'home/index'

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_authorization_check only: [:index, :back]

  def index
    session[:current_org]      = nil
    session[:current_building] = nil
    session[:current_floor]    = nil
    session[:sidebar]          = ''
  end

  def back
    if session[:back_url]
      redirect_to session[:back_url]
    else
      render action: :index
    end
  end

  def counter_cache_reset
    authorize! :read, User
    SpaceType.all.each do |st|
      SpaceType.reset_counters(st.id, :spaces)
    end
    Wing.all.each do |w|
      Wing.reset_counters(w.id, :floors)
    end
  end

  def import_data
    @import = Import.new
    authorize! :import, :database
  end

  def do_import_data
    @import = Import.new(import_params)
    authorize! :import, :database

    respond_to do |format|
      if @import.valid?
        format.html {
          @import.do_import
        }
      else
        format.html { render action: 'import_data' }
      end
    end
  end

  def backup
    authorize! :backup, :database

    data_dir = Rails.env.production? ? 'public/data' : "public/data_#{Rails.env}"
    backup_name = "tmp/spaceman_backup_#{Rails.env} #{DateTime.now.to_s.gsub(':', '.')}.zip"
    unless system "bundle", "exec", "rake", "db:dump"
      puts "!!!! Unable to run 'bundle exec rake db:dump': #{$?}"
    end
    unless system "zip", "-r", backup_name, data_dir, "db/data.yml" 
      puts "!!!! Unable to run 'zip -r #{backup_name} #{data_dir}': #{$?}"
    end
    send_file backup_name, disposition: :attachment
  end

  private
    def import_params
      params.require(:import).permit(:import_file)
    end
end

app/views/home/_dropdown_menu.html.haml
- if can? :update, User
  %li
    = link_to("<i class='fa fa-cogs'></i> #{t('.adjust_counters')}".html_safe, counter_cache_reset_home_index_path)
- if can? :import, :database
  %li
    = link_to("<i class='fa fa-database'></i> #{t('.import_data')}".html_safe, import_data_home_index_path)
- if can? :backup, :database
  %li
    = link_to("<i class='fa fa-database'></i> #{t('.backup_data')}".html_safe, backup_home_index_path)

app/views/home/_import_form.html.haml
= simple_form_for(@import, url: do_import_data_path(@import), multipart: true) do |f|
  = f.error_notification

  .form-inputs
    .panel.panel-default
      .panel-body
        = f.input :name
        = f.input :import_file, as: :file

  .form-actions
    = f.button :submit

app/views/home/counter_cache_reset.html.haml
%h3= t('.completed')

app/views/home/data_validation.html.haml
= render 'spaces/data_validation'

app/views/home/do_import_data.html.haml
%h3= t('.result_html', item: @import.name)

%ul
  - @import.result.each do |r|
    %li #{r}

app/views/home/import_data.html.haml
%h3= t('.import')

= render 'home/import_form'

app/views/home/index.html.haml
%h1= t('.title')
%h2= t('.version')
%br/
%br/
%h4= t('.welcome')

/[if lt IE 11]
  %h3{ class: "text-warning" }
    = t('.bad_version')

.spaceman
  %noscript
    %br/
    %br/
    %h3{ class: "text-danger" }
      = t('.javascript')

- content_for :left_side do

  %img{ src: "#{image_path 'mstile-70x70.png'}" }