config/routes.rb
Rails.application.routes.draw do
 
  root 'home#index'

  resources :specialties

  resources :moving_tasks

  resources :moving_items

  resources :table_defs

  resources :reports do
    member do
      get :prepare
      get :exec
    end
    collection do
      get :test
      get :icon_selector
    end
  end

  resources :wings

  resources :equipment_items

  resources :space_types

  resources :equipment_models do
    member do
      get :show_modal
    end
  end

  resources :equipment_groups

  resources :requirements do
    member do
      get :show_modal
      get :show_allocated_floors
    end
  end

  resources :spaces do
    member do
      get :show_modal
    end
  end

  resources :allocations do
    member do
      get :show_modal
    end
    collection do
      get :auto_new
    end
  end

  resources :people do
    member do
      get :show_modal
      get :show_allocated_floors
    end
  end

  resources :orgs do
    member do
      get :show_allocated_floors
      get :show_right
      get :export
    end
    collection do
      get :export_all
    end
  end

  resources :floors do
    member do
      get :drawing
      get :drawing_full
      get :drawing_allocations
      get :drawing_locator
      get :edit_spaces
      get :bulk_space_type_modal
      get :bulk_coor_adjust
      get :export
      post :bulk_space_type
    end
  end

  resources :buildings do
    member do
      get :photo
      get :export
    end
  end

  match 'do_import_data', to: 'home#do_import_data', via: :post

  resources :home, only: [ :index ] do
    collection do
      get :back
      get :counter_cache_reset
      get :import_data
      get :backup
    end
  end

  resources :users do
    member do
      get :change_password_for
      post :do_change_password_for
    end
    collection do
      get :change_password
      get :do_change_language
      patch :do_change_password
    end
  end

  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}

  get 'home/index'

  

end

app/models/building.rb
class Building < ApplicationRecord

  has_many :floors,       -> { order(:order, :name) },        inverse_of: :building, dependent: :destroy
  has_many :wings,        -> { order(:order, :name) }, inverse_of: :building, dependent: :destroy
  has_many :floor_images, -> { order(:level) },        inverse_of: :building, dependent: :destroy

  validates :name,  :short_name, presence: true, uniqueness: true
  validates :photo, :min_level, :max_level, presence: true
  validates :min_level, :max_level, numericality: true

  default_scope { order(:name) }

  scope :with_floors,      -> () { includes({wings: :floors}) }
  scope :with_allocations, -> (id) {
    where(id: id).includes({wings: {floors:
      [{spaces: [{allocations: [{person: :org}, {requirement: :org}]}, :space_type]}, :building, :wing] 
    }})
  }
  scope :with_spaces, -> (id) {
    where(id: id).includes({wings: {floors: {spaces: [:space_type]}}})
  }

  mount_uploader :photo, PhotoUploader

  accepts_nested_attributes_for :floor_images, allow_destroy: true
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  load_and_authorize_resource except: [:create, :export]

  before_action :set_back_url, only: [ :show ]

  def photo
    send_data(@building.photo,
              filename: @building.photo_filename,
              type: @building.photo_type,
              disposition: 'inline')
  end

  # GET /buildings
  # GET /buildings.json
  def index
    @buildings = @buildings.order(:name)
    session[:sidebar] = 'building'

    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.json { render json: @buildings }
    end
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
    session[:current_building] = @building.id
    session[:current_floor] = nil
    session[:sidebar] = 'building'

    respond_to do |format|
      format.html # show.html.erb
      format.js
      format.json { render json: @building }
    end
  end

  # GET /buildings/1/export.xml
  def export
    @building = Building.with_spaces(params[:id]).take
    authorize! :read, @building

    respond_to do |format|
      format.xml {
        send_data(
          @building.to_xml(
            except: [:id, :photo],
            include: [
              { wings: {
                except: [:id, :building_id],
                include: {
                  floors: {
                    except: [:id, :building_id, :wing_id, :drawing],
                    include: {
                      spaces: {
                        except: [:id, :space_type_id, :floor_id],
                        include: {space_type: {except: [:id, :space_count]}}}}}}}}]),
          filename: "building #{@building.short_name}.xml",
          type: :xml)
      }
    end
  end


  # GET /buildings/new
  # GET /buildings/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.js
      format.json { render json: @building }
    end
  end

  # GET /buildings/1/edit
  def edit
    respond_to do |format|
      format.js
      format.html
    end
  end

  # POST /buildings
  # POST /buildings.json
  def create
    @building = Building.new(building_params)
    authorize! :create, @building

    respond_to do |format|
      if @building.save
        format.html { redirect_to @building, notice: t('.create_ok', item: @building.name) }
        format.json { render json: @building, status: :created, location: @building }
      else
        format.html { render action: 'new' }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /buildings/1
  # PUT /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to @building, notice: t('.update_ok', item: @building.name) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    the_name = @building.name
    unless session[:current_building].nil?
      session[:current_building] = nil if session[:current_building].to_i == @building.id.to_i
    end
    @building.destroy
    respond_to do |format|
      format.html { redirect_to buildings_url, status: 303, notice: t('.delete_ok', item: the_name) }
      format.json { head :no_content }
    end
  end

  private

    def building_params
      params.require(:building).permit(
        :name, :short_name, :photo, :min_level, :max_level, :allocate_equipment,
        :moving_items, floor_images_attributes: [:id, :name, :level, :file, :_destroy])
    end
end

app/helpers/buildings_helper.rb
module BuildingsHelper

  def cache_key_for_buildings
    count          = Building.count
    max_updated_at = Building.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "buildings/all-#{count}-#{max_updated_at}"
  end

  # Build a hash of the building levels information to prepare the level drawings
  # on the sidebar. The data is supplied back as follow:
  #
  # [ [level, {floor_id => [locator_coor], ...} ...]
  #
  def levels_locations(building)
    data = {}
    levs = []
    level = building.min_level || 0
    Floor.where(building_id: building.id).order(:level).each do |floor|
      while level < floor.level
        levs << [level, data]
        data = {}
        level += 1
      end
      data[floor.id] = floor.locator_coor unless floor.locator_coor.blank?
    end
    clevel = level
    while level <= (building.max_level || clevel)
      levs << [level, data]
      data = {}
      level += 1
    end
    levs
  end
end

app/views/buildings/_dropdown_menu.html.haml
-# Dropdown menu for accessing the buildings in the navbar
-#
- Building.all.each do |b|
  %li= remote_link_to "<i class='fa fa-home'></i> #{h(b.name)}".html_safe, building_path(b)

app/views/buildings/_edit_link.html.haml
= remote_link_to('<i class="fa fa-edit"></i>'.html_safe,
    edit_building_path(edit_link),
    class: 'smallbtn',
    title: t('.title')) if can? :update, edit_link

app/views/buildings/_export_link.html.haml
= link_to("<i class='fa fa-arrow-right'></i> XML".html_safe, export_building_path(export_link, format: :xml), title: t('.title'), class: 'btn btn-primary btn-sm') if can? :read, export_link

app/views/buildings/_form.html.haml
= simple_form_for(@building, multipart: true) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, input_html: { class: 'large-field' }
    = f.input :short_name, input_html: { class: 'small-field' }
    = f.input :min_level, input_html: { class: 'small-field' }
    = f.input :max_level, input_html: { class: 'small-field' }
    = f.input :allocate_equipment
    = f.input :moving_items
    = f.input :photo, as: :file

    .panel.panel-default
      .panel-body
        .col-lg-12.col-sm-12
          %h4= t('.levels')
          %table#floor-images.nested-container
            %thead
              %tr
                %th.nowrap#level-nbr=           "* #{FloorImage.human_attribute_name(:level)}"
                %th.nowrap.hcenter#level-name=  "* #{FloorImage.human_attribute_name(:name)}"
                %th.nowrap#level-file=          "* #{FloorImage.human_attribute_name(:file)}"
                %th.hcenter#level-image=             FloorImage.human_attribute_name(:image)
                %th
            %tbody#floor-images-body
              = f.simple_fields_for :floor_images, wrapper: false do |fi|
                = render 'floor_image_fields', f: fi

          = link_to_add_association t('.add_level'), f, :floor_images, { 'data-association-insertion-node':   '#floor-images-body', 'data-association-insertion-method': 'append', class: 'btn btn-xs btn-default' }

  .form-actions
    = f.button :submit

app/views/buildings/_index.html.haml
.legend
  = render 'buildings/new_link'
  = Building.model_name.human(count: 2)

%table
  %thead
    %tr
      %th=         Building.human_attribute_name(:name)
      %th.hcenter= Building.human_attribute_name(:short_name)
      %th.hcenter= Building.human_attribute_name(:allocate_equipment)
      %th.hcenter= Building.human_attribute_name(:moving_items)
      %th.hcenter= Building.human_attribute_name(:photo)
      %th.no-print.nowrap

  %tbody
    - @buildings.each do |building|
      %tr
        %td= building.name
        %td.hcenter= building.short_name
        %td.hcenter= building.allocate_equipment? ? t('cmn.yes') : ''
        %td.hcenter= building.moving_items?       ? t('cmn.yes') : ''
        %td.hcenter= render partial: 'buildings/photo_thumb', object: building
        %td.no-print.nowrap= all_actions building, "[#{building.name}]"

app/views/buildings/_new.html.haml
.legend_u= t('.new')

= render 'form'

= link_to Building.model_name.human(count: 2), buildings_path

app/views/buildings/_new_link.html.haml
= link_to('<i class="fa fa-plus"></i>'.html_safe,
    new_building_path,
    class: 'smallbtn',
    title: t('.title')) if can? :create, Building

app/views/buildings/_photo_thumb.html.haml
%img{ src: photo_thumb.photo.url.to_s, class: 'img-thumbnail', style: 'width: 100px;' }

app/views/buildings/_show.html.haml
.legend_u
  = render partial: 'buildings/edit_link', object: @building
  %span= raw "#{t('activerecord.models.building')} <b>#{@building.name}</b>"
  = render partial: 'buildings/export_link', object: @building

= show_entry(@building) do |e|
  = e.field :name
  = e.field :short_name
  = e.field :min_level
  = e.field :max_level
  = e.field :allocate_equipment, as: :yesno
  = e.field :moving_items, as: :yesno

%br/
.legend_u
  = render partial: 'wings/new_wing_link', object: @building
  %span= t('.wings')

= render partial: 'wings/index', object: @building.wings

app/views/buildings/_sidebar.html.haml
-#
-# Left sidebar display of a building. This is triggered by the operator when he select a
-# building from the dropdown navbar menu
-#
- if bldg = Building.find(session[:current_building])
  .thumbnail
    %img{ src: bldg.photo_url.to_s, onclick: 'call_remote("#{building_path(bldg)}");' }
    .caption
      %h4= remote_link_to bldg.name, building_path(bldg)
      -# DO NOT DELETE THE COMMENTS!! - COULD BE REQUIRED SOMETIME...
      -#%hr
      -#%ul.list-unstyled
      -#  - bldg.wings.each do |wing|
      -#    - if wing.visible
      -#      %li= link_to "<b>#{wing.short_name}</b>".html_safe, wing_path(wing), style: "font-color: grey;"
      -#      - wing.floors.each do |floor|
      -#        %li= link_to floor.name, floor_path(floor), class: 'floor-link'
      -#    - else
      -#      - wing.floors.each do |floor|
      -#        %li= link_to floor.name, floor_path(floor)

  -#- levels.each do |level|
  -#  = render partial: 'buildings/sidebar_thumb', object: bldg, locals: { level: level, in_panels: false }

  #levels
    = render partial: 'buildings/sidebar_levels', object: bldg

app/views/buildings/_sidebar_levels.html.haml
-# Display drawings of building levels. When there is more than 4 potential levels, uses
-# labelled panels accordion to shrink the space required to keep the thumbs on the sidebar
- levels = levels_locations(sidebar_levels)
- if levels.size > 4
  .panel-group#locators
    .panel.panel-default
      - levels.each do |level|
        = render partial: 'buildings/sidebar_thumb', object: sidebar_levels, locals: { level: level, in_panels: true }
- else
  - levels.each do |level|
    = render partial: 'buildings/sidebar_thumb', object: sidebar_levels, locals: { level: level, in_panels: false }

app/views/buildings/_sidebar_thumb.html.haml
-# This generate a sidebar level picture with areas to permit floor selection by
-# the user. The level drawing is also highlighting the current displayed floor when required
-#
-# sidebar_thumb = building
-# level = [level_number, {floor_id => locator_coor, ...}
-# session[:current_floor]

- fi = FloorImage.where(building_id: sidebar_thumb.id, level: level[0]).take
- floor = Floor.find(session[:current_floor]) unless session[:current_floor].nil?
- unless fi.nil?
  - if in_panels
    .panel-heading
      %a.panel-toggle{ href: "#fi-#{fi.id}", 'data-toggle': 'collapse', 'data-parent': '#locators'}
        %h3.panel-title #{fi.name}
    .panel-body.collapse{ id: "fi-#{fi.id}", class: "#{'in' if floor && (floor.level == level[0]) }"}
      .panel-inner
        = render partial: 'buildings/thumb', object: sidebar_thumb, locals: { fi: fi, level: level, in_panels: in_panels }
  - else
    .thumbnail
      = render partial: 'buildings/thumb', object: sidebar_thumb, locals: { fi: fi, level: level, in_panels: in_panels }
      .caption{ style: 'text-align:center;'}= "#{fi.name}"

app/views/buildings/_thumb.html.haml
-# The thumb needs 'resize' class if displayed inside a panel such that it will be resized
-# through javascript at load time

-# The image is going to be adjusted in size through imagemapster (class resize-in-panel,
-# check_size function in spaceman.js). To limit flickering, css display is set to none
-# and adjusted to 'block' once resizing is done

- map_id = "locator-#{thumb.id}-#{level[0]}"
- if level[1][session[:current_floor]]
  %img{   src: "#{drawing_locator_floor_path(session[:current_floor])}?#{Time.now.to_i.to_s}",
       usemap: "##{map_id}",
        class: "img-map highlight#{' resize-in-panel' if in_panels}",
        style: "display: #{if in_panels then 'none' else 'block' end};",
           id: "img-#{thumb.id}-#{level[0]}" }
- else
  %img{   src: "#{fi.file.url}?#{Time.now.to_i.to_s}",
       usemap: "##{map_id}",
           id: "img-#{thumb.id}-#{level[0]}",
        style: "display: #{if in_panels then 'none' else 'block' end};",
        class: "img-map highlight#{' resize-in-panel' if in_panels}" }
%map{ id: "#{map_id}",
    name: "#{map_id}" }
  - level[1].each do |floor_id, locator_coor|
    %area{ shape: "#{locator_coor.split(',').size == 4 ? 'rect' : 'poly'}",
          coords: "#{locator_coor}",
            href: "#",
         onclick: "call_remote('#{floor_path(floor_id)}', {push: true})",
           style: 'cursor:pointer;'}

app/views/buildings/edit.js.erb
replace_content('#flash-pane', "<%= j(render(partial: 'layouts/flash')) %>");
replace_content('#left-pane',  "<%= j(render(partial: 'buildings/sidebar')) %>");
replace_content('#main-pane',  "<%= j(render(partial: 'buildings/edit')) %>");