config/routes.rb
Rails.application.routes.draw do
 
  root 'home#index'

  resources :specialties

  resources :moving_tasks

  resources :moving_items

  resources :table_defs

  resources :reports do
    member do
      get :prepare
      get :exec
    end
    collection do
      get :test
      get :icon_selector
    end
  end

  resources :wings

  resources :equipment_items

  resources :space_types

  resources :equipment_models do
    member do
      get :show_modal
    end
  end

  resources :equipment_groups

  resources :requirements do
    member do
      get :show_modal
      get :show_allocated_floors
    end
  end

  resources :spaces do
    member do
      get :show_modal
    end
  end

  resources :allocations do
    member do
      get :show_modal
    end
    collection do
      get :auto_new
    end
  end

  resources :people do
    member do
      get :show_modal
      get :show_allocated_floors
    end
  end

  resources :orgs do
    member do
      get :show_allocated_floors
      get :show_right
      get :export
    end
    collection do
      get :export_all
    end
  end

  resources :floors do
    member do
      get :drawing
      get :drawing_full
      get :drawing_allocations
      get :drawing_locator
      get :edit_spaces
      get :bulk_space_type_modal
      get :bulk_coor_adjust
      get :export
      post :bulk_space_type
    end
  end

  resources :buildings do
    member do
      get :photo
      get :export
    end
  end

  match 'do_import_data', to: 'home#do_import_data', via: :post

  resources :home, only: [ :index ] do
    collection do
      get :back
      get :counter_cache_reset
      get :import_data
      get :backup
    end
  end

  resources :users do
    member do
      get :change_password_for
      post :do_change_password_for
    end
    collection do
      get :change_password
      get :do_change_language
      patch :do_change_password
    end
  end

  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}

  get 'home/index'

  

end

app/models/report.rb
class Report < ApplicationRecord
  scope :all_reports, -> () { all.order(:group, :order, :name) }
  scope :alpha_list, -> () { all.order(:name) }

  validates :name, :order, presence: true
  validates :order, numericality: { only_integer: true }

  # Take care of the changes in the font_awsome icon names. Now, instead of
  # "icon-something" we must return "fa fa-something"
  def the_icon
    icon.sub(/^icon\-/, 'fa fa-')
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  load_and_authorize_resource except: [:create, :icon_selector, :prepare, :exec]

  #before_action :set_report, only: [:prepare, :exec, :show, :edit, :update, :destroy]

  def test
    respond_to do |format|
      format.js
    end
  end

  def icon_selector
    authorize! :read, Report
    respond_to do |format|
      format.html
      format.js
    end
  end

  def prepare
    @report = Report.find(params[:id])
    authorize! :read, @report

    if @report.params_script.blank?
      redirect_to exec_report_path(@report)
    end
  end

  def exec
    @report = Report.find(params[:id])
    authorize! :read, @report

    eval(@report.exec_script) unless @report.exec_script.blank?

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /reports
  # GET /reports.json
  def index
    @reports = @reports.alpha_list
    respond_to do |format|
      format.js
      format.html
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    respond_to do |format|
      format.js
      format.html
    end
  end

  # GET /reports/new
  def new
    respond_to do |format|
      format.js
      format.html
    end
  end

  # GET /reports/1/edit
  def edit
    respond_to do |format|
      format.js
      format.html
    end
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)
    authorize! :create, @report

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: t('.create_ok') }
        format.json { render action: 'show', status: :created, location: @report }
      else
        format.html { render action: 'new' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: t('.update_ok', item: @report.name) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    the_name = @report.name
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, status: 303, notice: t('.delete_ok', item: the_name) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:name, :group, :order, :icon, :params_script, :exec_script, :view_script, :enabled)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper

  def cache_key_for_reports
    count          = Report.count
    max_updated_at = Report.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "reports/all-#{count}-#{max_updated_at}"
  end

  def report_label(report, group)
    group.blank? ? '' : '&nbsp;&nbsp;&nbsp;' +
    "<i class='#{report.icon.blank? ? 'fa fa-print' : h(report.the_icon)}'></i>&nbsp;" +
    h(report.name) +
    (report.enabled? ? '' : " (#{t('cmn.disabled')})")
  end

  def icon_list
    %w[
      home building sitemap user group print gear gears truck archive bug square-o
      glass music search envelope-o heart star star-o film th-large th th-list check
      times search-plus search-minus power-off signal cog trash-o file-o clock-o road download
      arrow-circle-o-down arrow-circle-o-up inbox play-circle-o rotate-right repeat refresh list-alt
      lock flag headphones volume-off volume-down volume-up qrcode barcode tag tags book bookmark
      camera font bold italic text-height text-width align-left align-center align-right align-justify
      list dedent outdent indent video-camera image pencil map-marker adjust tint edit
      share-square-o check-square-o arrows step-backward fast-backward backward play
      pause stop forward fast-forward step-forward eject chevron-left chevron-right plus-circle
      minus-circle times-circle check-circle question-circle info-circle crosshairs times-circle-o
      check-circle-o ban arrow-left arrow-right arrow-up arrow-down mail-forward share expand compress
      plus minus asterisk exclamation-circle gift leaf fire eye eye-slash warning
      plane calendar random comment magnet chevron-up chevron-down retweet shopping-cart folder
      folder-open arrows-v arrows-h bar-chart twitter-square facebook-square camera-retro
      key cogs comments thumbs-o-up thumbs-o-down star-half heart-o sign-out linkedin-square
      thumb-tack external-link sign-in trophy github-square upload lemon-o phone bookmark-o
      phone-square twitter facebook github unlock credit-card rss hdd-o bullhorn bell
      certificate hand-o-right hand-o-left hand-o-up hand-o-down arrow-circle-left arrow-circle-right
      arrow-circle-up arrow-circle-down globe wrench tasks filter briefcase arrows-alt users
      link cloud flask cut copy paperclip save square navicon
      list-ul list-ol strikethrough underline table magic pinterest pinterest-square
      google-plus-square google-plus money caret-down caret-up caret-left caret-right columns unsorted
      sort sort-down sort-up envelope linkedin undo legal dashboard
      comment-o comments-o flash umbrella clipboard lightbulb-o exchange
      cloud-download cloud-upload user-md stethoscope suitcase bell-o coffee cutlery file-text-o
      building-o hospital-o ambulance medkit fighter-jet beer h-square plus-square angle-double-left
      angle-double-right angle-double-up angle-double-down angle-left angle-right angle-up angle-down
      desktop laptop tablet mobile-phone circle-o quote-left quote-right spinner circle
      reply github-alt folder-o folder-open-o smile-o frown-o meh-o gamepad keyboard-o flag-o
      flag-checkered terminal code reply-all star-half-empty
      location-arrow crop code-fork unlink question info exclamation superscript subscript
      eraser puzzle-piece microphone microphone-slash shield calendar-o fire-extinguisher rocket maxcdn
      chevron-circle-left chevron-circle-right chevron-circle-up chevron-circle-down html5 css3 anchor
      unlock-alt bullseye ellipsis-h ellipsis-v rss-square play-circle ticket minus-square minus-square-o
      level-up level-down check-square pencil-square external-link-square share-square compass toggle-down
      toggle-up toggle-right euro gbp dollar rupee yen rouble won bitcoin file file-text
      sort-alpha-asc sort-alpha-desc sort-amount-asc sort-amount-desc sort-numeric-asc sort-numeric-desc
      thumbs-up thumbs-down youtube-square youtube xing xing-square youtube-play dropbox stack-overflow
      instagram flickr adn bitbucket bitbucket-square tumblr tumblr-square long-arrow-down long-arrow-up
      long-arrow-left long-arrow-right apple windows android linux dribbble skype foursquare trello female
      male gittip gratipay sun-o moon-o vk weibo renren pagelines stack-exchange
      arrow-circle-o-right arrow-circle-o-left toggle-left caret-square-o-left dot-circle-o wheelchair
      vimeo-square turkish-lira try plus-square-o space-shuttle slack envelope-square wordpress openid
      bank graduation-cap yahoo google reddit reddit-square
      stumbleupon-circle stumbleupon delicious digg pied-piper-pp pied-piper-alt drupal joomla language
      fax child paw spoon cube cubes behance behance-square steam steam-square recycle
      car cab tree spotify deviantart soundcloud database file-pdf-o file-word-o
      file-excel-o file-powerpoint-o file-image-o file-archive-o
      file-sound-o file-video-o file-code-o vine codepen jsfiddle life-saver circle-o-notch rebel empire git-square
      git yc-square tencent-weibo qq wechat send
      send-o history circle-thin header paragraph sliders share-alt share-alt-square bomb
      soccer-ball-o futbol-o tty binoculars plug slideshare twitch yelp newspaper-o wifi calculator
      paypal google-wallet cc-visa cc-mastercard cc-discover cc-amex cc-paypal cc-stripe bell-slash
      bell-slash-o trash copyright at eyedropper paint-brush birthday-cake area-chart pie-chart
      line-chart lastfm lastfm-square toggle-off toggle-on bicycle bus ioxhost angellist cc shekel
      sheqel meanpath buysellads connectdevelop dashcube forumbee leanpub sellsy shirtsinbulk
      simplybuilt skyatlas cart-plus cart-arrow-down diamond ship user-secret motorcycle street-view
      heartbeat venus mars mercury intersex transgender transgender-alt venus-double mars-double
      venus-mars mars-stroke mars-stroke-v mars-stroke-h neuter genderless facebook-official pinterest-p
      whatsapp server user-plus user-times hotel viacoin train subway medium y-combinator
      optin-monster opencart expeditedssl battery-4 battery battery-full battery-3
      battery-three-quarters battery-2 battery-half battery-1 battery-quarter battery-0 battery-empty
      mouse-pointer i-cursor object-group object-ungroup sticky-note sticky-note-o cc-jcb cc-diners-club
      clone balance-scale hourglass-o hourglass-1 hourglass-2 hourglass-3
      hourglass hand-grab-o hand-stop-o hand-scissors-o
      hand-lizard-o hand-spock-o hand-pointer-o hand-peace-o trademark registered creative-commons gg
      gg-circle tripadvisor odnoklassniki odnoklassniki-square get-pocket wikipedia-w safari chrome
      firefox opera internet-explorer tv television contao 500px amazon calendar-plus-o
      calendar-minus-o calendar-times-o calendar-check-o industry map-pin map-signs map-o map commenting
      commenting-o houzz vimeo black-tie fonticons reddit-alien edge credit-card-alt codiepie modx
      fort-awesome usb product-hunt mixcloud scribd pause-circle pause-circle-o stop-circle
      stop-circle-o shopping-bag shopping-basket hashtag bluetooth bluetooth-b percent gitlab wpbeginner
      wpforms envira universal-access wheelchair-alt question-circle-o blind audio-description
      volume-control-phone braille assistive-listening-systems asl-interpreting deafness glide glide-g
      sign-language low-vision viadeo viadeo-square snapchat snapchat-ghost snapchat-square pied-piper
      first-order yoast themeisle google-plus-circle font-awesome handshake-o
      envelope-open envelope-open-o linode address-book address-book-o address-card
      address-card-o user-circle user-circle-o user-o id-badge id-card
      id-card-o quora free-code-camp telegram thermometer-4 thermometer-3 thermometer-2 thermometer-1
      thermometer-0 shower bathtub podcast window-maximize window-minimize
      window-restore window-close window-close-o bandcamp grav etsy
      imdb ravelry eercast microchip snowflake-o superpowers wpexplorer meetup
   ].map { |i|
      fa_icon "#{i} 2x", title: i, name:i
    }
  end

end

app/views/reports/_config_dropdown_menu.html.haml
- if can? :update, Report
  %li= remote_link_to "<i class=\"fa fa-print\"></i> #{Report.model_name.human.pluralize}".html_safe, reports_path

app/views/reports/_edit_link.html.haml
= remote_link_to('<i class="fa fa-edit"></i>'.html_safe,
    edit_report_path(edit_link),
    class: 'smallbtn',
    title: t('.title')) if can? :update, edit_link

app/views/reports/_form.html.haml
= simple_form_for(@report) do |f|
  = f.error_notification

  .form-inputs
    .tabbable
      %ul.nav.nav-tabs
        %li.active= link_to t('cmn.attributes'), '#attributes', 'data-toggle': :tab
        %li= link_to t('.params_script'), '#params-script', 'data-toggle': :tab
        %li= link_to t('.exec_script'), '#exec-script', 'data-toggle': :tab
        %li= link_to t('.view_script'), '#view-script', 'data-toggle': :tab
      .tab-content
        #attributes.tab-pane.active
          %br
          = f.input :name,  input_html: { class: 'large-field'}
          = f.input :enabled
          = f.input :group, input_html: { class: 'large-field'}
          = f.input :order, input_html: { class: 'small-field'}
          = f.input :icon, as: :hidden, input_html: { class: 'icon-field'}
          .form-group
            = label_tag 'the-icon', t('.icon'), class: 'control-label col-lg-3 col-sm-3'
            .controls.col-lg-9.col-sm-9
              %span#the-icon{ onclick: "call_remote('#{icon_selector_reports_path(format: :js)}');" }
                %i{ class: "#{@report.icon.blank? ? 'fa fa-print' : @report.the_icon} fa-2x"}
        #params-script.tab-pane
          %br
          = text_area_tag 'report[params_script]', @report.params_script, class: 'code-haml'
        #exec-script.tab-pane
          %br
          = text_area_tag 'report[exec_script]', @report.exec_script, class: 'code-ruby'
        #view-script.tab-pane
          %br
          = text_area_tag 'report[view_script]', @report.view_script, class: 'code-haml'


  .form-actions
    %br
    = f.button :submit

app/views/reports/_icon_selector.html.haml
.modal-header
  %button.close{ type: 'button', onclick: 'hide_modal(event);' } &times;
  %h3= t('.please_select')    
.modal-body
  .scrollable
    - icons = icon_list
    %table
      %thead
        %tr
          - (0..14).each do
            %th
      %tbody
        - count = 0
        - icons.each do |i|
          - if (count % 12) == 0
            - if count > 0
              </tr>
            <tr>
          = "<td onclick='selected_toggle(this)'>#{i}</td>".html_safe
          - count += 1
        - while (count % 12) != 0
          <td></td>
          - count += 1
.modal-footer
  %button{ class: 'btn btn-primary', onclick: 'hide_modal(event);' } Cancel
  %button{ class: 'btn btn-primary', onclick: 'icon_selected(event);' } Select

app/views/reports/_index.html.haml
.legend
  = render 'reports/new_link'
  = Report.model_name.human.pluralize

%table
  %thead
    %tr
      %th=         Report.human_attribute_name(:name)
      %th.hcenter= Report.human_attribute_name(:enabled)
      %th.hcenter= Report.human_attribute_name(:group)
      %th.hcenter= Report.human_attribute_name(:order)
      %th.hcenter= Report.human_attribute_name(:icon)
      %th.hcenter{ style: 'width: 30em;' }= Report.human_attribute_name(:view_script)
      %th.no-print

  %tbody
    - @reports.each do |report|
      %tr
        %td= report.name
        %td.hcenter= report.enabled? ? 'Yes' : 'No'
        %td.hcenter= report.group
        %td.hcenter= report.order
        %td.hcenter= report.icon.blank? ? "<i class='fa fa-print fa-2x'></i>".html_safe : "<i class='#{h(report.the_icon)} fa-2x'></i>".html_safe
        %td.highlight{ style: 'width: 40em;' }
          %pre{ style: 'width: 40em; background-color: #ddd;' }
            = format_code_to_html report.view_script
        %td.nowrap.no-print= all_actions report, "[#{report.name}]"

app/views/reports/_new.html.haml
%h1= t('.new')

= render 'form'

= remote_link_to t('cmn.back'), reports_path

app/views/reports/_new_link.html.haml
= remote_link_to('<i class="fa fa-plus"></i>'.html_safe,
    new_report_path,
    class: 'smallbtn',
    title: t('.title')) if can? :create, Report

app/views/reports/_reports_dropdown_menu.html.haml
- group = ''
- Report.all_reports.each do |report|
  - if report.enabled? || can?(:create, Report)
    - unless group == report.group
      - group = report.group
      %li= link_to "<b>#{group}:</b>".html_safe, '#'
    %li
      = link_to report_label(report, group).html_safe, prepare_report_path(report), remote: true

app/views/reports/_test.html.haml
.modal-header
  %button.close{ type: "button", onclick: 'hide_modal(event);' } &times;
  %h3 Bâtiments et Allocations
  %h4 Veuillez sélectionner les bâtiments désirés:
  = simple_form_for(:buildings,
                    url: exec_report_path(@report),
                    method: :get) do |f|
    .modal-body
      = f.error_notification

      .form-inputs
        = f.input 'selection',
            label: 'Bâtiments',
            collection: Building.all,
            as: :check_boxes,
            value_method: :id,
            label_method: :short_name
        .form-group
          %span.col-lg-3.col-sm-3
          .controls.col-lg-9.col-sm-9
            = link_to 'Tous', '#',
                class: 'smallbtn',
                onclick: '$("input.check_boxes").trigger("click"); return false;'
    .modal-footer
      = link_to 'Annule', '#',
          onclick: 'hide_modal(event);',
          class: 'btn btn-primary'
      = f.button :submit, 'Exécution'

app/views/reports/exec.js.erb
replace_content('#main-pane', "<%= j(render(inline: @report.view_script, type: :haml, layout: false)) %>");

app/views/reports/icon_selector.html.haml
= render 'reports/icon_selector'

app/views/reports/icon_selector.js.erb
replace_content('#flash-pane', "<%= j(render(partial: 'layouts/flash')) %>");
replace_content('#modal-info', "<%= j(render(partial: 'reports/icon_selector')) %>");
$('#modal-dialog').modal('show');

app/views/reports/prepare.js.erb
replace_content('#flash-pane', "<%= j(render(partial: 'layouts/flash')) %>");
replace_content('#modal-info', "<%= j(render inline: @report.params_script, type: :haml) %>");
$('#modal-dialog').modal({ backdrop: false, show: true});

app/views/reports/test.js.erb
replace_content('#flash-pane', "<%= j(render(partial: 'layouts/flash')) %>");
replace_content('#modal-info', "<%= j(render 'reports/test') %>");
$('#modal-dialog').modal({ backdrop: false, show: true});